"""Messages 3

Revision ID: 2694ccce78ab
Revises: 010ebd2b1095
Create Date: 2019-03-21 13:47:16.967058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2694ccce78ab'
down_revision = '010ebd2b1095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_column('messages', 'timestamp')
    # ### end Alembic commands ###
