"""Messages 4

Revision ID: f25823785a72
Revises: 2694ccce78ab
Create Date: 2019-03-21 13:48:36.761221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25823785a72'
down_revision = '2694ccce78ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('recipient_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['recipient_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'sender_id')
    op.drop_column('messages', 'recipient_id')
    # ### end Alembic commands ###
